### ISSUE TITLE
Text off-center

### ISSUE THREAD

**Issue by francozfr4** [mpm11011/ac7-ultrawide#14]
Hi! Just to preface, I don't really know anything about coding

I tried following the instructions as best I could. When I play, the ultrawide support is there (it looks AMAZING) but the text is off center. Do you have any tips on how to fix?

**Comment by martinsstuff** [comment]
Please post a screenshot of your Ace Combat 7 directory, usually this reveals where the issue lies.

**Comment by francozfr4** [comment]
Here you go! Sorry for the late reply
https://imgur.com/a/m7uU2RZ

**Comment by martinsstuff** [comment]
Classic case of old 3Dmigoto version, make sure to download version 1.3.16, the downloads aren't in chronological order because of how GitHub is ordering files in releases.

**Comment by francozfr4** [comment]
Ahhh damn, I'm an idiot lol...thanks for that!

**Comment by mpm11011** [comment]
Looks like this was solved.
