### ISSUE TITLE
10/2021 update has broken patcher

### ISSUE THREAD

**Issue by adshlkads1000** [mpm11011/ac7-ultrawide#23]
The removal of denuvo update has caused the ultrawide patcher to cease functioning, error message application load error 3:0000065432

**Comment by 1992Andrew** [comment]
Same for me, I'm relived, I was starting to think it was just me.

**Comment by WinkelCode** [comment]
Please check this comment for a workaround: https://github.com/mpm11011/ac7-ultrawide/issues/22#issuecomment-947551619
