### ISSUE TITLE
New HUD elements in SP Mission 1

### ISSUE THREAD

**Issue by mpm11011** [mpm11011/ac7-ultrawide#5]
Which means I have to do some more shader hunting. Need to find the map background and character portrait background, just like in mission 7.

**Comment by normalranger** [comment]
Hey, not sure if the comment section is explicitly development related, but I'd like to drop a thanks nevertheless for your continuous work to fix ultrawide for ac7. This is my favourite franchise so this means a lot to me! Keep it up and good luck!

**Comment by mpm11011** [comment]
Thank you!

**Comment by mpm11011** [comment]
Fixed with PR #8.
